name = 'Minmer'
license = 'MIT'
licenselink = 'https://github.com/kramerc/hugo-theme-minmer/LICENSE'
description = 'A minimalistic foundation for your Hugo site'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/kramerc/hugo-theme-minmer'

# If you have a running demo of the theme
demosite = 'https://kramerc.github.io/hugo-theme-minmer'

# Taxonomy terms
tags = ['blog', 'personal']
features = []

[author]
  name = 'Kramer Campbell'
  homepage = 'https://kramerc.com/'
